package parser;

import node.Node;

//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

public Node nval;
//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public ParserVal()
{
	System.out.println("ParserVal created.");
}
/**
 * Initialize me as an int
 */
public ParserVal(int val)
{
  ival=val;
  System.out.println("ParserVal created for Int.");
}

/**
 * Initialize me as a double
 */
public ParserVal(double val)
{
  dval=val;
  System.out.println("ParserVal created for Double.");
}

/**
 * Initialize me as a string
 */
public ParserVal(String val)
{
	System.out.println("Parser val sval = " + val);
  sval=val;
  System.out.println("ParserVal created for String.");
}

/**
 * Initialize me as an Object
 */
public ParserVal(Object val)
{
  obj=val;
  System.out.println("ParserVal created for Object.");
}

public ParserVal(Node val)
{	
  nval = val;
  System.out.println("ParserVal created for Node.");
}

public Node getNval(){
	return this.nval;
}


	public Node getNode() {
		return nval;	
	}


}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
